// Auto-generated from CSV - do not edit manually
// Generated: 2025-11-25T16:45:53.728Z

/* clang-format off */

{"enableHeatpumpResetAllAlarms", REG_COIL_STATUS, 3, 4, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Reset all alarms"},
{"enableHeatpumpInternalAdditionalHeater", REG_COIL_STATUS, 4, 5, 1, MODEL_INVERTER, "Heatpump", "Unit", "Enable internal additional heater"},
{"enableHeatpumpExternalAdditionalHeater", REG_COIL_STATUS, 5, 6, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable external additional heater"},
{"enableTapwaterHgw", REG_COIL_STATUS, 6, 7, 1, MODEL_INVERTER, "Tapwater", "HGW", "Enable HGW"},
{"enableHeatpumpFlowPressureSwitch", REG_COIL_STATUS, 7, 8, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable flow switch/pressure switch"},
{"enableHeatpumpTapWater", REG_COIL_STATUS, 8, 9, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable tap water"},
{"enableHeatpumpHeat", REG_COIL_STATUS, 9, 10, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable heat"},
{"enableCoolingActiveCooling", REG_COIL_STATUS, 10, 11, 1, MODEL_MEGA | MODEL_INVERTER, "Cooling", "Unit", "Enable active cooling"},
{"enableHeatingMixValve1", REG_COIL_STATUS, 11, 12, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Enable mix valve 1"},
{"enableTapwaterTwc", REG_COIL_STATUS, 12, 13, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "Enable TWC"}, {"enableTapwaterWcs", REG_COIL_STATUS, 13, 14, 1, MODEL_MEGA, "Tapwater", "WCS", "Enable WCS"},
{"enableTapwaterHotGasPump", REG_COIL_STATUS, 14, 15, 1, MODEL_MEGA, "Tapwater", "Unit", "Enable hot gas pump"},
{"enableHeatingMixValve2", REG_COIL_STATUS, 16, 17, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Enable mix valve 2 (EM)"},
{"enableHeatingMixValve3", REG_COIL_STATUS, 17, 18, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Enable mix valve 3 (EM)"},
{"enableHeatingMixValve4", REG_COIL_STATUS, 18, 19, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Enable mix valve 4 (EM)"},
{"enableHeatingMixValve5", REG_COIL_STATUS, 19, 20, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Enable mix valve 5 (EM)"},
{"enableHeatpumpBrineOutMonitoring", REG_COIL_STATUS, 20, 21, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable brine out monitoring"},
{"enableHeatpumpBrinePumpContinuousOperation", REG_COIL_STATUS, 21, 22, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable brine pump continuous operation"},
{"enableHeatpumpSystemCirculationPump", REG_COIL_STATUS, 22, 23, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable system circulation pump"},
{"enableCoolingDewPointCalculation", REG_COIL_STATUS, 23, 24, 1, MODEL_MEGA, "Cooling", "CoolingCircuit", "Enable dew point calculation"},
{"enableTapwaterAntiLegionella", REG_COIL_STATUS, 24, 25, 1, MODEL_INVERTER, "Tapwater", "Unit", "Enable anti legionella"},
{"enableHeatpumpAdditionalHeaterOnly", REG_COIL_STATUS, 25, 26, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable additional heater only (No compressor). Requires Operation mode: Standby"},
{"enableElectricCurrentLimitation", REG_COIL_STATUS, 26, 27, 1, MODEL_INVERTER, "Electric", "Unit", "Enable current limitation"},
{"enablePoolPool", REG_COIL_STATUS, 28, 29, 1, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Enable pool (EM)"},
{"enableCoolingSurplusHeatChiller", REG_COIL_STATUS, 29, 30, 1, MODEL_MEGA, "Cooling", "SurplusHeat", "Enable surplus heat, chiller (no borehole)"},
{"enableCoolingSurplusHeatBorehole", REG_COIL_STATUS, 30, 31, 1, MODEL_MEGA, "Cooling", "Unit", "Enable surplus heat, borehole (no chiller)"},
{"enablePoolExternalAdditionalHeater", REG_COIL_STATUS, 31, 32, 1, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Enable external additional heater for pool (EM)"},
{"enablePoolInternalAdditionalHeater", REG_COIL_STATUS, 32, 33, 1, MODEL_INVERTER, "Pool", "Unit", "Enable internal additional heater for pool (EM)"},
{"enableCoolingPassiveCooling", REG_COIL_STATUS, 33, 34, 1, MODEL_MEGA | MODEL_INVERTER, "Cooling", "Unit", "Enable passive cooling (EM)"},
{"enableHeatpumpVariableSpeedCondenserPump", REG_COIL_STATUS, 34, 35, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable variable speed mode for condenser pump"},
{"enableHeatpumpVariableSpeedBrinePump", REG_COIL_STATUS, 35, 36, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable variable speed mode for brine pump"},
{"enableHeatingMixValve1CoolingMode", REG_COIL_STATUS, 36, 37, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Enable cooling mode for mixing valve 1"},
{"enableHeatingMixValve1OutdoorTempCooling", REG_COIL_STATUS, 37, 38, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Enable outdoor temp dependent for cooling with mixing valve 1"},
{"enableHeatingMixValve1BrinePumpOnCooling", REG_COIL_STATUS, 38, 39, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Enable internal brine pump to start when cooling is active for mixing valve 1"},
{"enableHeatpumpOutdoorTempExternalHeater", REG_COIL_STATUS, 39, 40, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable outdoor temp dependent for external heater"},
{"enableHeatpumpBrineInMonitoring", REG_COIL_STATUS, 40, 41, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable brine in monitoring"},
{"enableHeatingFixedSystemSupplySetPoint", REG_COIL_STATUS, 41, 42, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Enable fixed system supply set point, allows defacto address 40117"},
{"enableHeatpumpEvaporatorFreezeProtection", REG_COIL_STATUS, 42, 43, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Enable evaporator freeze protection"},
{"enableHeatingMixValve2OutdoorTempCooling", REG_COIL_STATUS, 43, 44, 1, MODEL_MEGA, "Heating", "MixValve2", "Enable outdoor temp dependent for cooling with mixing valve 2 (EM3 only)"},
{"enableHeatingMixValve2DewPointCalculation", REG_COIL_STATUS, 44, 45, 1, MODEL_MEGA, "Heating", "MixValve2", "Enable dew point calculation on mixing valve 2, requires room sensor for mixing valve 2 (EM3 only)"},
{"enableHeatingMixValve2OutdoorTempHeating", REG_COIL_STATUS, 45, 46, 1, MODEL_MEGA, "Heating", "MixValve2", "Enable outdoor temp dependent for heating with mixing valve 2 (EM3 only)"},
{"enableHeatingMixValve3OutdoorTempCooling", REG_COIL_STATUS, 46, 47, 1, MODEL_MEGA, "Heating", "MixValve3", "Enable outdoor temp dependent for cooling with mixing valve 3 (EM3 only)"},
{"enableHeatingMixValve3DewPointCalculation", REG_COIL_STATUS, 47, 48, 1, MODEL_MEGA, "Heating", "MixValve3", "Enable dew point calculation on mixing valve 3, requires room sensor for mixing valve 3 (EM3 only)"},
{"enableHeatingMixValve3OutdoorTempHeating", REG_COIL_STATUS, 48, 49, 1, MODEL_MEGA, "Heating", "MixValve3", "Enable outdoor temp dependent for heating with mixing valve 3 (EM3 only)"},
{"enableHeatingMixValve4OutdoorTempCooling", REG_COIL_STATUS, 49, 50, 1, MODEL_MEGA, "Heating", "MixValve4", "Enable outdoor temp dependent for cooling with mixing valve 4 (EM3 only)"},
{"enableHeatingMixValve4DewPointCalculation", REG_COIL_STATUS, 50, 51, 1, MODEL_MEGA, "Heating", "MixValve4", "Enable dew point calculation on mixing valve 4, requires room sensor for mixing valve 4 (EM3 only)"},
{"enableHeatingMixValve4OutdoorTempHeating", REG_COIL_STATUS, 51, 52, 1, MODEL_MEGA, "Heating", "MixValve4", "Enable outdoor temp dependent for heating with mixing valve 4 (EM3 only)"},
{"enableHeatingMixValve5OutdoorTempCooling", REG_COIL_STATUS, 52, 53, 1, MODEL_MEGA, "Heating", "MixValve5", "Enable outdoor temp dependent for cooling with mixing valve 5 (EM3 only)"},
{"enableHeatingMixValve5DewPointCalculation", REG_COIL_STATUS, 53, 54, 1, MODEL_MEGA, "Heating", "MixValve5", "Enable dew point calculation on mixing valve 5, requires room sensor for mixing valve 5 (EM3 only)"},
{"enableHeatingMixValve5OutdoorTempHeating", REG_COIL_STATUS, 54, 55, 1, MODEL_MEGA, "Heating", "MixValve5", "Enable outdoor temp dependent for heating with mixing valve 5 (EM3 only)"},
{"enableHeatingMixValve2BrinePumpOnCooling", REG_COIL_STATUS, 55, 56, 1, MODEL_MEGA, "Heating", "MixValve2", "Enable internal brine pump to start when cooling is active for mixing valve 2 (EM3 only)"},
{"enableHeatingMixValve3BrinePumpOnCooling", REG_COIL_STATUS, 56, 57, 1, MODEL_MEGA, "Heating", "MixValve3", "Enable internal brine pump to start when cooling is active for mixing valve 3 (EM3 only)"},
{"enableHeatingMixValve4BrinePumpOnCooling", REG_COIL_STATUS, 57, 58, 1, MODEL_MEGA, "Heating", "MixValve4", "Enable internal brine pump to start when cooling is active for mixing valve 4 (EM3 only)"},
{"enableHeatingMixValve5BrinePumpOnCooling", REG_COIL_STATUS, 58, 59, 1, MODEL_MEGA, "Heating", "MixValve5", "Enable internal brine pump to start when cooling is active for mixing valve 5 (EM3 only)"},
{"alarmHeatpumpClassA", REG_INPUT_STATUS, 0, 10001, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Alarm active, Class: A"},
{"alarmHeatpumpClassB", REG_INPUT_STATUS, 1, 10002, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Alarm active, Class: B"},
{"alarmHeatpumpClassC", REG_INPUT_STATUS, 2, 10003, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Alarm active, Class: C"},
{"alarmHeatpumpClassDGenesisSecondary", REG_INPUT_STATUS, 3, 10004, 1, MODEL_MEGA, "Heatpump", "Unit", "Alarm active, Class: D - Genesis secondary"},
{"alarmHeatpumpClassELegacySecondary", REG_INPUT_STATUS, 4, 10005, 1, MODEL_MEGA, "Heatpump", "Unit", "Alarm active, Class: E - Legacy secondary"},
{"alarmHeatpumpHighPressureSwitch", REG_INPUT_STATUS, 9, 10010, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "High pressure switch alarm"},
{"alarmHeatpumpLowPressureLevel", REG_INPUT_STATUS, 10, 10011, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Low pressure level alarm"},
{"alarmHeatpumpHighDischargePipeTemperature", REG_INPUT_STATUS, 11, 10012, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "High discharge pipe temperature alarm"},
{"alarmHeatpumpOperatingPressureLimit", REG_INPUT_STATUS, 12, 10013, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Operating pressure limit indication"},
{"alarmHeatpumpDischargePipeSensor", REG_INPUT_STATUS, 13, 10014, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Discharge pipe sensor alarm"},
{"alarmHeatpumpLiquidLineSensor", REG_INPUT_STATUS, 14, 10015, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Liquid line sensor alarm"},
{"alarmHeatpumpSuctionGasSensor", REG_INPUT_STATUS, 15, 10016, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Suction gas sensor alarm"},
{"alarmHeatpumpFlowPressureSwitch", REG_INPUT_STATUS, 16, 10017, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Flow/pressure switch alarm"},
{"alarmHeatpumpPowerInputPhaseDetection", REG_INPUT_STATUS, 22, 10023, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Power input phase detection alarm"},
{"alarmHeatpumpInverterUnit", REG_INPUT_STATUS, 23, 10024, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Inverter unit alarm"},
{"alarmHeatingSystemSupplyLowTemperature", REG_INPUT_STATUS, 24, 10025, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "System supply low temperature alarm"},
{"alarmHeatpumpCompressorLowSpeed", REG_INPUT_STATUS, 25, 10026, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor low speed alarm"},
{"alarmHeatpumpLowSuperHeat", REG_INPUT_STATUS, 26, 10027, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Low super heat alarm"},
{"alarmHeatpumpPressureRatioOutOfRange", REG_INPUT_STATUS, 27, 10028, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Pressure ratio out of range alarm"},
{"alarmHeatpumpCompressorPressureOutsideEnvelope", REG_INPUT_STATUS, 28, 10029, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor pressure outside envelope alarm"},
{"alarmHeatpumpBrineTemperatureOutOfRange", REG_INPUT_STATUS, 29, 10030, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine temperature out of range alarm"},
{"alarmHeatpumpBrineInSensor", REG_INPUT_STATUS, 30, 10031, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine in sensor alarm"},
{"alarmHeatpumpBrineOutSensor", REG_INPUT_STATUS, 31, 10032, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine out sensor alarm"},
{"alarmHeatpumpCondenserInSensor", REG_INPUT_STATUS, 32, 10033, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Condenser in sensor alarm"},
{"alarmHeatpumpCondenserOutSensor", REG_INPUT_STATUS, 33, 10034, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Condenser out sensor alarm"},
{"alarmHeatpumpOutdoorSensor", REG_INPUT_STATUS, 34, 10035, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Outdoor sensor alarm"},
{"alarmHeatingSystemSupplyLineSensor", REG_INPUT_STATUS, 35, 10036, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "System supply line sensor alarm"},
{"alarmHeatingMixValve1SupplyLineSensor", REG_INPUT_STATUS, 36, 10037, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Mix valve 1 supply line sensor alarm"},
{"alarmHeatingMixValve2SupplyLineSensor", REG_INPUT_STATUS, 37, 10038, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Mix valve 2 supply line sensor alarm (EM)"},
{"alarmHeatingMixValve3SupplyLineSensor", REG_INPUT_STATUS, 38, 10039, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Mix valve 3 supply line sensor alarm (EM)"},
{"alarmHeatingMixValve4SupplyLineSensor", REG_INPUT_STATUS, 39, 10040, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Mix valve 4 supply line sensor alarm (EM)"},
{"alarmHeatingMixValve5SupplyLineSensor", REG_INPUT_STATUS, 40, 10041, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Mix valve 5 supply line sensor alarm (EM)"},
{"alarmTapwaterWcsReturnLineSensor", REG_INPUT_STATUS, 44, 10045, 1, MODEL_MEGA, "Tapwater", "WCS", "WCS return line sensor alarm (EM)"},
{"alarmTapwaterTwcSupplyLineSensor", REG_INPUT_STATUS, 45, 10046, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC supply line sensor alarm (EM)"},
{"alarmCoolingTankSensor", REG_INPUT_STATUS, 46, 10047, 1, MODEL_MEGA, "Cooling", "CoolingTank", "Cooling tank sensor alarm (EM)"},
{"alarmCoolingSupplyLineSensor", REG_INPUT_STATUS, 47, 10048, 1, MODEL_MEGA | MODEL_INVERTER, "Cooling", "CoolingTank", "Cooling supply line sensor alarm (EM)"},
{"alarmCoolingCircuitReturnLineSensor", REG_INPUT_STATUS, 48, 10049, 1, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling circuit return line sensor alarm (EM)"},
{"alarmHeatpumpBrineDeltaOutOfRange", REG_INPUT_STATUS, 49, 10050, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine delta out of range alarm"},
{"alarmTapwaterMidSensor", REG_INPUT_STATUS, 50, 10051, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "Unit", "Tap water mid sensor alarm"},
{"alarmTapwaterTwcCirculationReturnSensor", REG_INPUT_STATUS, 51, 10052, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC circulation return sensor alarm (EM)"},
{"alarmTapwaterHgwSensor", REG_INPUT_STATUS, 52, 10053, 1, MODEL_INVERTER, "Tapwater", "HGW", "HGW sensor alarm"},
{"alarmHeatpumpInternalAdditionalHeater", REG_INPUT_STATUS, 53, 10054, 1, MODEL_INVERTER, "Heatpump", "Unit", "Internal additional heater alarm"},
{"alarmHeatpumpBrineInHighTemperature", REG_INPUT_STATUS, 55, 10056, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine in high temperature alarm"},
{"alarmHeatpumpBrineInLowTemperature", REG_INPUT_STATUS, 56, 10057, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine in low temperature alarm"},
{"alarmHeatpumpBrineOutLowTemperature", REG_INPUT_STATUS, 57, 10058, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine out low temperature alarm"},
{"alarmTapwaterTwcCirculationReturnLowTemperature", REG_INPUT_STATUS, 58, 10059, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC circulation return low temperature alarm (EM)"},
{"alarmTapwaterTwcSupplyLowTemperature", REG_INPUT_STATUS, 59, 10060, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC supply low temperature alarm (EM)"},
{"alarmHeatingMixValve1SupplyTemperatureDeviation", REG_INPUT_STATUS, 60, 10061, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Mix valve 1 supply temperature deviation alarm"},
{"alarmHeatingMixValve2SupplyTemperatureDeviation", REG_INPUT_STATUS, 61, 10062, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Mix valve 2 supply temperature deviation alarm (EM)"},
{"alarmHeatingMixValve3SupplyTemperatureDeviation", REG_INPUT_STATUS, 62, 10063, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Mix valve 3 supply temperature deviation alarm (EM)"},
{"alarmHeatingMixValve4SupplyTemperatureDeviation", REG_INPUT_STATUS, 63, 10064, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Mix valve 4 supply temperature deviation alarm (EM)"},
{"alarmHeatingMixValve5SupplyTemperatureDeviation", REG_INPUT_STATUS, 64, 10065, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Mix valve 5 supply temperature deviation alarm (EM)"},
{"alarmTapwaterWcsReturnLineTemperatureDeviation", REG_INPUT_STATUS, 65, 10066, 1, MODEL_MEGA, "Tapwater", "WCS", "WCS return line temperature deviation alarm (EM)"},
{"alarmHeatpumpSum", REG_INPUT_STATUS, 66, 10067, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Sum alarm"},
{"alarmCoolingCircuitSupplyLineTemperatureDeviation", REG_INPUT_STATUS, 67, 10068, 1, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling circuit supply line temperature deviation alarm (EM)"},
{"alarmCoolingTankTemperatureDeviation", REG_INPUT_STATUS, 68, 10069, 1, MODEL_MEGA, "Cooling", "CoolingTank", "Cooling tank temperature deviation alarm (EM)"},
{"alarmCoolingSurplusHeatTemperatureDeviation", REG_INPUT_STATUS, 69, 10070, 1, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat temperature deviation alarm (EM)"},
{"alarmCoolingHumidityRoomSensor", REG_INPUT_STATUS, 70, 10071, 1, MODEL_MEGA, "Cooling", "CoolingCircuit", "Humidity room sensor alarm"},
{"alarmCoolingSurplusHeatSupplyLineSensor", REG_INPUT_STATUS, 71, 10072, 1, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat supply line sensor alarm (EM)"},
{"alarmCoolingSurplusHeatReturnLineSensor", REG_INPUT_STATUS, 72, 10073, 1, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat return line sensor alarm (EM)"},
{"alarmCoolingTankReturnLineSensor", REG_INPUT_STATUS, 73, 10074, 1, MODEL_MEGA, "Cooling", "CoolingTank", "Cooling tank return line sensor alarm (EM)"},
{"alarmHeatingTemperatureRoomSensor", REG_INPUT_STATUS, 74, 10075, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Temperature room sensor alarm"},
{"alarmHeatpumpInverterUnitCommunication", REG_INPUT_STATUS, 75, 10076, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Inverter unit communication alarm"},
{"alarmPoolReturnLineSensor", REG_INPUT_STATUS, 76, 10077, 1, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Pool return line sensor alarm"},
{"statusPoolExternalStop", REG_INPUT_STATUS, 77, 10078, 1, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "External stop for pool, read only"},
{"statusCoolingExternalStartBrinePump", REG_INPUT_STATUS, 78, 10079, 1, MODEL_MEGA | MODEL_INVERTER, "Cooling", "Unit", "External start brine pump, read only"},
{"statusHeatpumpExternalRelayBrineGroundWaterPump", REG_INPUT_STATUS, 79, 10080, 1, MODEL_MEGA, "Heatpump", "Unit", "External relay for brine/ground water pump."},
{"alarmTapwaterEndTankSensor", REG_INPUT_STATUS, 81, 10082, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "Tap water end tank sensor alarm"},
{"alarmTapwaterMaxTimeAntiLegionellaExceeded", REG_INPUT_STATUS, 82, 10083, 1, MODEL_INVERTER, "Tapwater", "Unit", "Maximum time for anti-legionella exceeded alarm"},
{"alarmHeatpumpGenesisSecondaryUnitCommunication", REG_INPUT_STATUS, 83, 10084, 1, MODEL_MEGA, "Heatpump", "Unit", "Genesis secondary unit alarm - this specific secondary unit can't communicate with its primary unit"},
{"alarmHeatpumpPrimaryUnitNetworkConflict", REG_INPUT_STATUS, 84, 10085, 1, MODEL_MEGA, "Heatpump", "Unit", "Primary unit alarm - the primary has detected other primary units on the same network with a network mask that is allowing conflict. Change network settings in order to avoid problem. For instance change port number on the primary " "and its secondary unit."},
{"alarmHeatpumpPrimaryUnitSecondariesNotDetected", REG_INPUT_STATUS, 85, 10086, 1, MODEL_MEGA, "Heatpump", "Unit", "Primary unit alarm - the primary has not detected all secondary units. Make sure that the primary/secondary settings are correct and the network mask and port and number of Genesis secondaries settings are correct."},
{"statusHeatpumpOilBoostInProgress", REG_INPUT_STATUS, 86, 10087, 1, MODEL_INVERTER, "Heatpump", "Unit", "Oil boost in progress"},
{"statusHeatpumpCompressorControl", REG_INPUT_STATUS, 199, 10200, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor control signal"},
{"statusHeatpumpSmartGrid1Evu", REG_INPUT_STATUS, 201, 10202, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Smart Grid 1, EVU input"},
{"statusHeatpumpExternalAlarmInput", REG_INPUT_STATUS, 202, 10203, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External alarm input"},
{"statusHeatpumpSmartGrid2", REG_INPUT_STATUS, 204, 10205, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Smart Grid 2"},
{"statusHeatpumpExternalAdditionalHeaterControl", REG_INPUT_STATUS, 206, 10207, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External additional heater control signal"},
{"statusHeatingMixValve1CirculationPumpControl", REG_INPUT_STATUS, 209, 10210, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Mix valve 1 circulation pump control signal"},
{"statusHeatpumpCondenserPumpOnOff", REG_INPUT_STATUS, 210, 10211, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Condenser pump On/off control"},
{"statusHeatingSystemCirculationPumpControl", REG_INPUT_STATUS, 211, 10212, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "System circulation pump control signal"},
{"statusTapwaterHotGasCirculationPumpControl", REG_INPUT_STATUS, 213, 10214, 1, MODEL_MEGA, "Tapwater", "Unit", "Hot gas circulation pump control signal"},
{"statusHeatpumpBrinePumpOnOff", REG_INPUT_STATUS, 218, 10219, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine pump On/off control"},
{"statusHeatpumpExternalHeaterCirculationPumpControl", REG_INPUT_STATUS, 219, 10220, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External heater circulation pump control signal"},
{"statusHeatingSeasonWinterActive", REG_INPUT_STATUS, 220, 10221, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heating season (winter) active"},
{"statusHeatpumpExternalAdditionalHeaterActive", REG_INPUT_STATUS, 221, 10222, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External additional heater active"},
{"statusHeatpumpInternalAdditionalHeaterActive", REG_INPUT_STATUS, 222, 10223, 1, MODEL_INVERTER, "Heatpump", "Unit", "Internal additional heater active"},
{"statusTapwaterHgwRegulationControl", REG_INPUT_STATUS, 223, 10224, 1, MODEL_INVERTER, "Tapwater", "HGW", "HGW regulation control signal"},
{"statusHeatpumpStopping", REG_INPUT_STATUS, 224, 10225, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Heat pump stopping"},
{"statusHeatpumpOkToStart", REG_INPUT_STATUS, 225, 10226, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Heat pump OK to start"},
{"statusTapwaterTwcSupplyLineCirculationPumpControl", REG_INPUT_STATUS, 230, 10231, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC supply line circulation pump control signal (EM)"},
{"statusTapwaterWcsRegulationControl", REG_INPUT_STATUS, 232, 10233, 1, MODEL_MEGA, "Tapwater", "WCS", "WCS regulation control signal (EM)"},
{"statusTapwaterWcsCirculationPumpControl", REG_INPUT_STATUS, 233, 10234, 1, MODEL_MEGA, "Tapwater", "WCS", "WCS circulation pump control signal (EM)"},
{"statusTapwaterTwcEndTankHeaterControl", REG_INPUT_STATUS, 234, 10235, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC end tank heater control signal (EM)"},
{"statusPoolDirectionalValvePosition", REG_INPUT_STATUS, 235, 10236, 1, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Pool directional valve position (EM)"},
{"statusCoolingCircuitCirculationPumpControl", REG_INPUT_STATUS, 236, 10237, 1, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling circuit circulation pump control signal (EM)"},
{"statusPoolCirculationPumpControl", REG_INPUT_STATUS, 237, 10238, 1, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Pool circulation pump control signal (EM)"},
{"statusCoolingSurplusHeatDirectionalValvePosition", REG_INPUT_STATUS, 238, 10239, 1, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat directional valve position (EM)"},
{"statusCoolingSurplusHeatCirculationPumpControl", REG_INPUT_STATUS, 239, 10240, 1, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat circulation pump control signal (EM)"},
{"statusCoolingCircuitRegulationControl", REG_INPUT_STATUS, 240, 10241, 1, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling circuit regulation control signal (EM)"},
{"statusCoolingSurplusHeatRegulationControl", REG_INPUT_STATUS, 241, 10242, 1, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat regulation control signal (EM)"},
{"statusCoolingActiveCoolingDirectionalValvePosition", REG_INPUT_STATUS, 242, 10243, 1, MODEL_MEGA, "Cooling", "CoolingTank", "Active cooling directional valve position (Borehole disconnected) (EM)"},
{"statusCoolingPassiveActiveCoolingDirectionalValvePosition", REG_INPUT_STATUS, 243, 10244, 1, MODEL_MEGA, "Cooling", "CoolingTank", "Passive/Active cooling directional valve position (Cooling tank connected) (EM)"},
{"statusPoolRegulationControl", REG_INPUT_STATUS, 244, 10245, 1, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Pool regulation control signal (EM)"},
{"statusHeatingMixValve1ProducingPassiveCooling", REG_INPUT_STATUS, 245, 10246, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Indication when mixing valve 1 is producing passive cooling"},
{"statusHeatpumpCompressorUnableToSpeedUp", REG_INPUT_STATUS, 246, 10247, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor is unable to speed up"},
{"valueHeatpumpCurrentlyRunningFirstPrioritisedDemand", REG_INPUT, 1, 30002, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Currently running: First prioritised demand *1"},
{"valueHeatpumpCompressorAvailableGears", REG_INPUT, 4, 30005, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor available gears *3"},
{"valueHeatpumpCompressorSpeedRpm", REG_INPUT, 5, 30006, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor speed RPM"},
{"valueHeatpumpExternalAdditionalHeaterCurrentDemand", REG_INPUT, 6, 30007, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External additional heater: Current demand (%)"},
{"valueHeatpumpDischargePipeTemperature", REG_INPUT, 7, 30008, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Discharge pipe temperature"},
{"valueHeatpumpCondenserInTemperature", REG_INPUT, 8, 30009, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Condenser in temperature"},
{"valueHeatpumpCondenserOutTemperature", REG_INPUT, 9, 30010, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Condenser out temperature"},
{"valueHeatpumpBrineInTemperature", REG_INPUT, 10, 30011, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine in temperature"},
{"valueHeatpumpBrineOutTemperature", REG_INPUT, 11, 30012, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine out temperature"},
{"valueHeatingSystemSupplyLineTemperature", REG_INPUT, 12, 30013, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "System supply line temperature"},
{"valueHeatpumpOutdoorTemperature", REG_INPUT, 13, 30014, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Outdoor temperature"},
{"valueTapwaterTopTemperature", REG_INPUT, 15, 30016, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "Unit", "Tap water top temperature"},
{"valueTapwaterLowerTemperature", REG_INPUT, 16, 30017, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "Unit", "Tap water lower temperature"},
{"valueTapwaterWeightedTemperature", REG_INPUT, 17, 30018, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "Unit", "Tap water weighted temperature"},
{"valueHeatingSystemSupplyLineCalculatedSetPoint", REG_INPUT, 18, 30019, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "System supply line calculated set point"},
{"valueHeatingSelectedHeatCurveSystemSupplyLine", REG_INPUT, 19, 30020, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Selected heat curve, (system) supply line"},
{"valueHeatingHeatCurveXCoordinate1", REG_INPUT, 20, 30021, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heat curve, X-coordinate 1 (highest outdoor temperature)"},
{"valueHeatingHeatCurveXCoordinate2", REG_INPUT, 21, 30022, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heat curve, X-coordinate 2"},
{"valueHeatingHeatCurveXCoordinate3", REG_INPUT, 22, 30023, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heat curve, X-coordinate 3"},
{"valueHeatingHeatCurveXCoordinate4", REG_INPUT, 23, 30024, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heat curve, X-coordinate 4"},
{"valueHeatingHeatCurveXCoordinate5", REG_INPUT, 24, 30025, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heat curve, X-coordinate 5"},
{"valueHeatingHeatCurveXCoordinate6", REG_INPUT, 25, 30026, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heat curve, X-coordinate 6"},
{"valueHeatingHeatCurveXCoordinate7", REG_INPUT, 26, 30027, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heat curve, X-coordinate 7 (lowest outdoor temperature)"},
{"valueCoolingSeasonIntegralValue", REG_INPUT, 36, 30037, 1, MODEL_MEGA | MODEL_INVERTER, "Cooling", "Unit", "Cooling season integral value"},
{"valueHeatpumpCondenserCirculationPumpSpeed", REG_INPUT, 39, 30040, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Condenser circulation pump speed (%)"},
{"valueHeatingMixValve1SupplyLineTemperature", REG_INPUT, 40, 30041, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Mix valve 1 supply line temperature"},
{"valueHeatingBufferTankTemperature", REG_INPUT, 41, 30042, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Buffer tank temperature"},
{"valueHeatingMixValve1Position", REG_INPUT, 43, 30044, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Mix valve 1 position"},
{"valueHeatpumpBrineCirculationPumpSpeed", REG_INPUT, 44, 30045, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine circulation pump speed (%)"},
{"valueTapwaterHgwSupplyLineTemperature", REG_INPUT, 45, 30046, 100, MODEL_INVERTER, "Tapwater", "HGW", "HGW supply line temperature"},
{"valueTapwaterHgwDirectionalValvePosition", REG_INPUT, 47, 30048, 1, MODEL_MEGA, "Tapwater", "HGW", "Hot water directional valve position (%)"},
{"valueHeatpumpCompressorOperatingHoursMsb", REG_INPUT, 48, 30049, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor operating hours (MSB)"},
{"valueHeatpumpCompressorOperatingHoursLsb", REG_INPUT, 49, 30050, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor operating hours (LSB)"},
{"valueTapwaterOperatingHoursMsb", REG_INPUT, 50, 30051, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "Unit", "Tap water operating hours (MSB)"},
{"valueTapwaterOperatingHoursLsb", REG_INPUT, 51, 30052, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "Unit", "Tap water operating hours (LSB)"},
{"valueHeatpumpExternalAdditionalHeaterOperatingHoursMsb", REG_INPUT, 52, 30053, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External additional heater operating hours (MSB)"},
{"valueHeatpumpExternalAdditionalHeaterOperatingHoursLsb", REG_INPUT, 53, 30054, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External additional heater operating hours (LSB)"},
{"valueHeatpumpCompressorSpeedPercent", REG_INPUT, 54, 30055, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor speed percent"},
{"valueHeatpumpCurrentlyRunningSecondPrioritisedDemand", REG_INPUT, 55, 30056, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Currently running: Second prioritised demand *1"},
{"valueHeatpumpCurrentlyRunningThirdPrioritisedDemand", REG_INPUT, 56, 30057, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Currently running: Third prioritised demand *1"},
{"valueHeatpumpSoftwareVersionMajor", REG_INPUT, 57, 30058, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Software version: Major"},
{"valueHeatpumpSoftwareVersionMinor", REG_INPUT, 58, 30059, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Software version: Minor"},
{"valueHeatpumpSoftwareVersionMicro", REG_INPUT, 59, 30060, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Software version: Micro"},
{"valueHeatpumpCompressorTemporarilyBlocked", REG_INPUT, 60, 30061, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor temporarily blocked, (start restriction timer)"},
{"valueHeatpumpCompressorCurrentGear", REG_INPUT, 61, 30062, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Compressor current gear"},
{"valueHeatpumpQueuedDemandFirstPriority", REG_INPUT, 62, 30063, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Queued demand, first priority *1"},
{"valueHeatpumpQueuedDemandSecondPriority", REG_INPUT, 63, 30064, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Queued demand, second priority *1"},
{"valueHeatpumpQueuedDemandThirdPriority", REG_INPUT, 64, 30065, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Queued demand, third priority *1"},
{"valueHeatpumpQueuedDemandFourthPriority", REG_INPUT, 65, 30066, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Queued demand, fourth priority *1"},
{"valueHeatpumpQueuedDemandFifthPriority", REG_INPUT, 66, 30067, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Queued demand, fifth priority *1"},
{"valueHeatpumpInternalAdditionalHeaterCurrentStep", REG_INPUT, 67, 30068, 1, MODEL_INVERTER, "Heatpump", "Unit", "Internal additional heater current step"},
{"valueHeatingBufferTankChargeSetPoint", REG_INPUT, 68, 30069, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Buffer tank charge set point"},
{"valueElectricMeterL1Current", REG_INPUT, 69, 30070, 100, MODEL_INVERTER, "Electric", "Unit", "Electric meter L1 current (A)"},
{"valueElectricMeterL2Current", REG_INPUT, 70, 30071, 100, MODEL_INVERTER, "Electric", "Unit", "Electric meter L2 current (A)"},
{"valueElectricMeterL3Current", REG_INPUT, 71, 30072, 100, MODEL_INVERTER, "Electric", "Unit", "Electric meter L3 current (A)"},
{"valueElectricMeterL1ToNeutralVoltage", REG_INPUT, 72, 30073, 100, MODEL_INVERTER, "Electric", "Unit", "Electric meter L1-0 voltage (V)"},
{"valueElectricMeterL2ToNeutralVoltage", REG_INPUT, 73, 30074, 100, MODEL_INVERTER, "Electric", "Unit", "Electric meter L2-0 voltage (V)"},
{"valueElectricMeterL3ToNeutralVoltage", REG_INPUT, 74, 30075, 100, MODEL_INVERTER, "Electric", "Unit", "Electric meter L3-0 voltage (V)"},
{"valueElectricMeterL1ToL2Voltage", REG_INPUT, 75, 30076, 10, MODEL_INVERTER, "Electric", "Unit", "Electric meter L1-L2 voltage (V)"},
{"valueElectricMeterL2ToL3Voltage", REG_INPUT, 76, 30077, 10, MODEL_INVERTER, "Electric", "Unit", "Electric meter L2-L3 voltage (V)"},
{"valueElectricMeterL3ToL1Voltage", REG_INPUT, 77, 30078, 10, MODEL_INVERTER, "Electric", "Unit", "Electric meter L3-L1 voltage (V)"},
{"valueElectricMeterL1Power", REG_INPUT, 78, 30079, 1, MODEL_INVERTER, "Electric", "Unit", "Electric meter L1 power (W)"},
{"valueElectricMeterL2Power", REG_INPUT, 79, 30080, 1, MODEL_INVERTER, "Electric", "Unit", "Electric meter L2 power (W)"},
{"valueElectricMeterL3Power", REG_INPUT, 80, 30081, 1, MODEL_INVERTER, "Electric", "Unit", "Electric meter L3 power (W)"},
{"valueElectricMeterValue", REG_INPUT, 81, 30082, 1, MODEL_INVERTER, "Electric", "Unit", "Electric meter - meter value (kWh)"},
{"valueHeatpumpComfortMode", REG_INPUT, 82, 30083, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Comfort mode *4"},
{"valueElectricMeterKwhTotalLsb", REG_INPUT, 83, 30084, 10, MODEL_INVERTER, "Electric", "Unit", "Electric meter kWh total (LSB)"},
{"valueElectricMeterKwhTotalMsb", REG_INPUT, 84, 30085, 10, MODEL_INVERTER, "Electric", "Unit", "Electric meter kWh total (MSB)"},
{"valueTapwaterWcsValvePosition", REG_INPUT, 85, 30086, 100, MODEL_MEGA, "Tapwater", "WCS", "WCS valve position (EM)"},
{"valueTapwaterTwcValvePosition", REG_INPUT, 86, 30087, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC valve position (EM)"},
{"valueHeatingMixValve2Position", REG_INPUT, 87, 30088, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Mix valve 2 position (EM)"},
{"valueHeatingMixValve3Position", REG_INPUT, 88, 30089, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Mix valve 3 position (EM)"},
{"valueHeatingMixValve4Position", REG_INPUT, 89, 30090, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Mix valve 4 position (EM)"},
{"valueHeatingMixValve5Position", REG_INPUT, 90, 30091, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Mix valve 5 position (EM)"},
{"valueCoolingDewPointRoom", REG_INPUT, 91, 30092, 100, MODEL_MEGA, "Cooling", "CoolingCircuit", "Dew point room (EM)"},
{"valueCoolingSupplyLineMixValvePosition", REG_INPUT, 92, 30093, 100, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling supply line mix valve position (EM)"},
{"valueCoolingSurplusHeatFanSpeed", REG_INPUT, 93, 30094, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat fan speed (EM)"},
{"valuePoolSupplyLineMixValvePosition", REG_INPUT, 94, 30095, 100, MODEL_MEGA, "Pool", "Unit", "Pool supply line mix valve position (EM)"},
{"valueTapwaterTwcSupplyLineTemperature", REG_INPUT, 95, 30096, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC supply line temperature (EM)"},
{"valueTapwaterTwcReturnTemperature", REG_INPUT, 96, 30097, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC return temperature (EM)"},
{"valueTapwaterWcsReturnLineTemperature", REG_INPUT, 97, 30098, 100, MODEL_MEGA, "Tapwater", "WCS", "WCS return line temperature (EM)"},
{"valueTapwaterTwcEndTankTemperature", REG_INPUT, 98, 30099, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC end tank temperature (EM)"},
{"valueHeatingMixValve2SupplyLineTemperature", REG_INPUT, 99, 30100, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Mix valve 2 supply line temperature (EM)"},
{"valueHeatingMixValve3SupplyLineTemperature", REG_INPUT, 100, 30101, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Mix valve 3 supply line temperature (EM)"},
{"valueHeatingMixValve4SupplyLineTemperature", REG_INPUT, 101, 30102, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Mix valve 4 supply line temperature (EM)"},
{"valueCoolingCircuitReturnLineTemperature", REG_INPUT, 103, 30104, 100, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling circuit return line temperature (EM)"},
{"valueCoolingTankTemperature", REG_INPUT, 104, 30105, 100, MODEL_MEGA, "Cooling", "CoolingTank", "Cooling tank temperature (EM)"},
{"valueCoolingTankReturnLineTemperature", REG_INPUT, 105, 30106, 100, MODEL_MEGA, "Cooling", "CoolingTank", "Cooling tank return line temperature (EM)"},
{"valueCoolingCircuitSupplyLineTemperature", REG_INPUT, 106, 30107, 100, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling circuit supply line temperature (EM)"},
{"valueHeatingMixValve5SupplyLineTemperature", REG_INPUT, 107, 30108, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Mix valve 5 supply line temperature (EM)"},
{"valueHeatingMixValve2ReturnLineTemperature", REG_INPUT, 109, 30110, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Mix valve 2 return line temperature (EM)"},
{"valueHeatingMixValve3ReturnLineTemperature", REG_INPUT, 111, 30112, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Mix valve 3 return line temperature (EM)"},
{"valueHeatingMixValve4ReturnLineTemperature", REG_INPUT, 113, 30114, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Mix valve 4 return line temperature (EM)"},
{"valueHeatingMixValve5ReturnLineTemperature", REG_INPUT, 115, 30116, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Mix valve 5 return line temperature (EM)"},
{"valueCoolingSurplusHeatReturnLineTemperature", REG_INPUT, 117, 30118, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat return line temperature (EM)"},
{"valueCoolingSurplusHeatSupplyLineTemperature", REG_INPUT, 118, 30119, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat supply line temperature (EM)"},
{"valuePoolSupplyLineTemperature", REG_INPUT, 119, 30120, 100, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Pool supply line temperature (EM)"},
{"valuePoolReturnLineTemperature", REG_INPUT, 120, 30121, 100, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Pool return line temperature (EM)"},
{"valueHeatingRoomTemperatureSensor", REG_INPUT, 121, 30122, 10, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Room temperature sensor"},
{"valueHeatpumpBubblePointHighPressureTemperature", REG_INPUT, 122, 30123, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Bubble point, high pressure temperature"},
{"valueHeatpumpDewPointHighPressureTemperature", REG_INPUT, 123, 30124, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Dew point, high pressure temperature"},
{"valueHeatpumpDewPointLowPressureTemperature", REG_INPUT, 124, 30125, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Dew point, low pressure temperature"},
{"valueHeatpumpSuperheatTemperature", REG_INPUT, 125, 30126, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Superheat temperature"},
{"valueHeatpumpSubCoolingTemperature", REG_INPUT, 126, 30127, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Sub cooling temperature"},
{"valueHeatpumpLowPressureSidePressure", REG_INPUT, 127, 30128, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Low pressure side, pressure (bar(g))"},
{"valueHeatpumpHighPressureSidePressure", REG_INPUT, 128, 30129, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "High pressure side, pressure (bar(g))"},
{"valueHeatpumpLiquidLineTemperature", REG_INPUT, 129, 30130, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Liquid line temperature"},
{"valueHeatpumpSuctionGasTemperature", REG_INPUT, 130, 30131, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Suction gas temperature"},
{"valueHeatingSeasonIntegralValue", REG_INPUT, 131, 30132, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heating season integral value"},
{"valueHeatpumpPidPValue", REG_INPUT, 132, 30133, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "P - value for gear shifting and demand calculation"},
{"valueHeatpumpPidIValue", REG_INPUT, 133, 30134, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "I - value for gear shifting and demand calculation"},
{"valueHeatpumpPidDValue", REG_INPUT, 134, 30135, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "D - value for gear shifting and demand calculation"},
{"valueHeatpumpBufferTankIValue", REG_INPUT, 135, 30136, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "I - value for compressor ON/OFF (Buffer tank)"},
{"valueHeatpumpBufferTankPValue", REG_INPUT, 136, 30137, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "P - value for compressor ON/OFF (Buffer tank)"},
{"valueHeatingMixValveCoolingOpeningDegree", REG_INPUT, 137, 30138, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Mix valve cooling opening degree (EM2/3)"},
{"valueTapwaterDesiredGear", REG_INPUT, 139, 30140, 1, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "Unit", "Desired gear for tap water"},
{"valueHeatingDesiredGear", REG_INPUT, 140, 30141, 1, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Desired gear for heating"},
{"valueCoolingDesiredGear", REG_INPUT, 141, 30142, 1, MODEL_MEGA | MODEL_INVERTER, "Cooling", "Unit", "Desired gear for cooling"},
{"valuePoolDesiredGear", REG_INPUT, 142, 30143, 1, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Desired gear for pool"},
{"valueHeatpumpNumberOfAvailableSecondariesGenesis", REG_INPUT, 143, 30144, 1, MODEL_MEGA, "Heatpump", "Unit", "Number of available secondaries Genesis"},
{"valueHeatpumpNumberOfAvailableSecondariesLegacy", REG_INPUT, 144, 30145, 1, MODEL_MEGA, "Heatpump", "Unit", "Number of available secondaries Legacy"},
{"valueHeatpumpTotalDistributedGearsAllUnits", REG_INPUT, 145, 30146, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Total distributed gears to all units"},
{"valueHeatpumpMaximumGearCurrentlyRequested", REG_INPUT, 146, 30147, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Maximum gear out of all the currently requested gears"},
{"valueHeatingMixValve1DesiredTemperature", REG_INPUT, 147, 30148, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Desired temperature distribution circuit Mix valve 1"},
{"valueHeatingMixValve2DesiredTemperature", REG_INPUT, 148, 30149, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Desired temperature distribution circuit Mix valve 2"},
{"valueHeatingMixValve3DesiredTemperature", REG_INPUT, 149, 30150, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Desired temperature distribution circuit Mix valve 3"},
{"valueHeatingMixValve4DesiredTemperature", REG_INPUT, 150, 30151, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Desired temperature distribution circuit Mix valve 4"},
{"valueHeatingMixValve5DesiredTemperature", REG_INPUT, 151, 30152, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Desired temperature distribution circuit Mix valve 5"},
{"valueTapwaterHgwDisconnectEndTank", REG_INPUT, 152, 30153, 1, MODEL_MEGA, "Tapwater", "HGW", "Disconnect hot gas end tank, 0 = connected, 1 = disconnected"},
{"valueHeatpumpLegacyCompressorRunning", REG_INPUT, 153, 30154, 1, MODEL_MEGA, "Heatpump", "Unit", "Legacy heat pump compressor running (bit field)"},
{"valueHeatpumpLegacyReportingAlarm", REG_INPUT, 154, 30155, 1, MODEL_MEGA, "Heatpump", "Unit", "Legacy heat pump reporting alarm (bit field)"},
{"valueHeatpumpLegacyStartSignal", REG_INPUT, 155, 30156, 1, MODEL_MEGA, "Heatpump", "Unit", "Legacy heat pump start signal (bit field)"},
{"valueHeatpumpLegacyTapWaterSignal", REG_INPUT, 156, 30157, 1, MODEL_MEGA, "Heatpump", "Unit", "Legacy heat pump tap water signal (bit field)"},
{"valueHeatpumpPrimaryUnitAlarmClassDCombined", REG_INPUT, 160, 30161, 1, MODEL_MEGA, "Heatpump", "Unit", "Primary unit alarm - the combined output of all Class D alarms. This signal is a bit field, one bit for each secondary heat pump unit."},
{"valueHeatpumpPrimaryUnitAlarmLostCommunicationGenesis", REG_INPUT, 161, 30162, 1, MODEL_MEGA, "Heatpump", "Unit", "Primary unit alarm - the primary unit has lost communication with one or more Genesis secondaries. This signal is a bit field, one bit for each heat pump."},
{"valueHeatpumpPrimaryUnitAlarmClassASecondary", REG_INPUT, 162, 30163, 1, MODEL_MEGA, "Heatpump", "Unit", "Primary unit alarm - Class A alarm detected on the Genesis secondary heat pump unit. This signal is a bit field, one bit for each secondary heat pump unit."},
{"valueHeatpumpPrimaryUnitAlarmClassBSecondary", REG_INPUT, 163, 30164, 1, MODEL_MEGA, "Heatpump", "Unit", "Primary unit alarm - Class B alarm detected on the Genesis secondary heat pump unit. This signal is a bit field, one bit for each secondary heat pump unit."},
{"valueHeatpumpPrimaryUnitAlarmClassECombined", REG_INPUT, 170, 30171, 1, MODEL_MEGA, "Heatpump", "Unit", "Primary unit alarm - the combined output of all Class E alarms. This signal is a bit field, one bit for each legacy secondary heat pump unit."},
{"valueHeatpumpPrimaryUnitAlarmLegacyGeneral", REG_INPUT, 171, 30172, 1, MODEL_MEGA, "Heatpump", "Unit", "Primary unit alarm - general legacy heat pump alarm. This signal is a bit field, one bit for each legacy secondary heat pump unit. Detects if the sum alarm of the secondary unit is active."},
{"valueHeatpumpPrimaryUnitAlarmLegacyExpansionCardCommunication", REG_INPUT, 173, 30174, 1, MODEL_MEGA, "Heatpump", "Unit", "Primary unit alarm - the primary unit can not communicate with the corresponding expansion card for the legacy heat pump. This signal is a bit field, one bit for each legacy secondary heat pump unit."},
{"setHeatpumpOperationalMode", REG_HOLDING, 0, 40001, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Operational mode *2"},
{"setHeatingMaxLimitationSetPointCurveRadiator", REG_HOLDING, 3, 40004, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Max limitation, set point curve radiator"},
{"setHeatingMinLimitationSetPointCurveRadiator", REG_HOLDING, 4, 40005, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Min limitation, set point curve radiator"},
{"setHeatingComfortWheelSetting", REG_HOLDING, 5, 40006, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Comfort wheel setting"},
{"setHeatingHeatCurveYCoordinate1", REG_HOLDING, 6, 40007, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Set point heat curve, Y-coordinate 1 (highest outdoor temperature)"},
{"setHeatingHeatCurveYCoordinate2", REG_HOLDING, 7, 40008, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Set point heat curve, Y-coordinate 2"},
{"setHeatingHeatCurveYCoordinate3", REG_HOLDING, 8, 40009, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Set point heat curve, Y-coordinate 3"},
{"setHeatingHeatCurveYCoordinate4", REG_HOLDING, 9, 40010, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Set point heat curve, Y-coordinate 4"},
{"setHeatingHeatCurveYCoordinate5", REG_HOLDING, 10, 40011, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Set point heat curve, Y-coordinate 5"},
{"setHeatingHeatCurveYCoordinate6", REG_HOLDING, 11, 40012, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Set point heat curve, Y-coordinate 6"},
{"setHeatingHeatCurveYCoordinate7", REG_HOLDING, 12, 40013, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Set point heat curve, Y-coordinate 7 (lowest outdoor temperature)"},
{"setHeatingSeasonStopTemperature", REG_HOLDING, 16, 40017, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Heating season stop temperature"},
{"setTapwaterStartTemperature", REG_HOLDING, 22, 40023, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "Unit", "Start temperature tap water"},
{"setTapwaterStopTemperature", REG_HOLDING, 23, 40024, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "Unit", "Stop temperature tap water"},
{"setHeatpumpMinAllowedGearHeating", REG_HOLDING, 26, 40027, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Minimum allowed gear in heating *3"},
{"setHeatpumpMaxAllowedGearHeating", REG_HOLDING, 27, 40028, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Maximum allowed gear in heating *3"},
{"setHeatpumpMaxAllowedGearTapWater", REG_HOLDING, 28, 40029, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Maximum allowed gear in tap water *3"},
{"setHeatpumpMinAllowedGearTapWater", REG_HOLDING, 29, 40030, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Minimum allowed gear in tap water *3"},
{"setCoolingMixValveSetPoint", REG_HOLDING, 30, 40031, 100, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling mix valve set point (EM)"},
{"setTapwaterTwcMixValveSetPoint", REG_HOLDING, 31, 40032, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC mix valve set point (EM)"},
{"setTapwaterWcsReturnLineSetPoint", REG_HOLDING, 32, 40033, 100, MODEL_MEGA, "Tapwater", "WCS", "WCS return line set point (EM)"},
{"setTapwaterTwcMixValveLowestAllowedOpeningDegree", REG_HOLDING, 33, 40034, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC mix valve lowest allowed opening degree (EM)"},
{"setTapwaterTwcMixValveHighestAllowedOpeningDegree", REG_HOLDING, 34, 40035, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC mix valve highest allowed opening degree (EM)"},
{"setTapwaterTwcStartTemperatureImmersionHeater", REG_HOLDING, 35, 40036, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC start temperature immersion heater (EM)"},
{"setTapwaterTwcStartDelayImmersionHeater", REG_HOLDING, 36, 40037, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC start delay immersion heater, seconds (EM)"},
{"setTapwaterTwcStopTemperatureImmersionHeater", REG_HOLDING, 37, 40038, 100, MODEL_MEGA | MODEL_INVERTER, "Tapwater", "TWC", "TWC stop temperature immersion heater (EM)"},
{"setTapwaterWcsMixValveLowestAllowedOpeningDegree", REG_HOLDING, 38, 40039, 100, MODEL_MEGA, "Tapwater", "WCS", "WCS mix valve lowest allowed opening degree (EM)"},
{"setTapwaterWcsMixValveHighestAllowedOpeningDegree", REG_HOLDING, 39, 40040, 100, MODEL_MEGA, "Tapwater", "WCS", "WCS mix valve highest allowed opening degree (EM)"},
{"setHeatingMixValve2LowestAllowedOpeningDegree", REG_HOLDING, 40, 40041, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Mix valve 2 lowest allowed opening degree (EM)"},
{"setHeatingMixValve2HighestAllowedOpeningDegree", REG_HOLDING, 41, 40042, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Mix valve 2 highest allowed opening degree (EM)"},
{"setHeatingMixValve3LowestAllowedOpeningDegree", REG_HOLDING, 42, 40043, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Mix valve 3 lowest allowed opening degree (EM)"},
{"setHeatingMixValve3HighestAllowedOpeningDegree", REG_HOLDING, 43, 40044, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Mix valve 3 highest allowed opening degree (EM)"},
{"setHeatingMixValve4LowestAllowedOpeningDegree", REG_HOLDING, 44, 40045, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Mix valve 4 lowest allowed opening degree (EM)"},
{"setHeatingMixValve4HighestAllowedOpeningDegree", REG_HOLDING, 45, 40046, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Mix valve 4 highest allowed opening degree (EM)"},
{"setHeatingMixValve5LowestAllowedOpeningDegree", REG_HOLDING, 46, 40047, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Mix valve 5 lowest allowed opening degree (EM)"},
{"setHeatingMixValve5HighestAllowedOpeningDegree", REG_HOLDING, 47, 40048, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Mix valve 5 highest allowed opening degree (EM)"},
{"setCoolingSurplusHeatChillerSetPoint", REG_HOLDING, 48, 40049, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat chiller set point (EM)"},
{"setCoolingSupplyLineMixValveLowestAllowedOpeningDegree", REG_HOLDING, 49, 40050, 100, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling supply line mix valve: Lowest allowed opening degree (EM)"},
{"setCoolingSupplyLineMixValveHighestAllowedOpeningDegree", REG_HOLDING, 50, 40051, 100, MODEL_MEGA, "Cooling", "CoolingCircuit", "Cooling supply line mix valve: Highest allowed opening degree (EM)"},
{"setCoolingSurplusHeatOpeningDegreeStartFan1", REG_HOLDING, 51, 40052, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat opening degree for starting fan 1 (EM)"},
{"setCoolingSurplusHeatOpeningDegreeStartFan2", REG_HOLDING, 52, 40053, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat opening degree for starting fan 2 (EM)"},
{"setCoolingSurplusHeatOpeningDegreeStopFan1", REG_HOLDING, 53, 40054, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat opening degree for stopping fan 1 (EM)"},
{"setCoolingSurplusHeatOpeningDegreeStopFan2", REG_HOLDING, 54, 40055, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat opening degree for stopping fan 2 (EM)"},
{"setCoolingSurplusHeatLowestAllowedOpeningDegree", REG_HOLDING, 55, 40056, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat lowest allowed opening degree (EM)"},
{"setCoolingSurplusHeatHighestAllowedOpeningDegree", REG_HOLDING, 56, 40057, 100, MODEL_MEGA, "Cooling", "SurplusHeat", "Surplus heat highest allowed opening degree (EM)"},
{"setPoolChargeSetPoint", REG_HOLDING, 58, 40059, 100, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Pool charge set point (EM)"},
{"setPoolMixValveLowestAllowedOpeningDegree", REG_HOLDING, 59, 40060, 100, MODEL_MEGA, "Pool", "Unit", "Pool mix valve lowest allowed opening degree (EM)"},
{"setPoolMixValveHighestAllowedOpeningDegree", REG_HOLDING, 60, 40061, 100, MODEL_MEGA, "Pool", "Unit", "Pool mix valve highest allowed opening degree (EM)"},
{"setHeatpumpGearShiftDelayHeating", REG_HOLDING, 61, 40062, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Gear shift delay heating"},
{"setHeatpumpGearShiftDelayPool", REG_HOLDING, 62, 40063, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Gear shift delay pool"},
{"setHeatpumpGearShiftDelayCooling", REG_HOLDING, 63, 40064, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Gear shift delay cooling"},
{"setHeatpumpBrineInHighAlarmLimit", REG_HOLDING, 67, 40068, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine in high alarm limit"},
{"setHeatpumpBrineInLowAlarmLimit", REG_HOLDING, 68, 40069, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine in low alarm limit"},
{"setHeatpumpBrineOutLowAlarmLimit", REG_HOLDING, 69, 40070, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine out low alarm limit"},
{"setHeatpumpBrineMaxDeltaLimit", REG_HOLDING, 70, 40071, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine max delta limit"},
{"setTapwaterHgwPumpStartTemperatureDischargePipe", REG_HOLDING, 71, 40072, 100, MODEL_MEGA, "Tapwater", "HGW", "Hot gas pump start temperature discharge pipe"},
{"setTapwaterHgwPumpLowerStopLimitTemperatureDischargePipe", REG_HOLDING, 72, 40073, 100, MODEL_MEGA, "Tapwater", "HGW", "Hot gas pump lower stop limit temperature discharge pipe"},
{"setTapwaterHgwPumpUpperStopLimitTemperatureDischargePipe", REG_HOLDING, 73, 40074, 100, MODEL_MEGA, "Tapwater", "HGW", "Hot gas pump upper stop limit temperature discharge pipe"},
{"setHeatpumpExternalAdditionalHeaterStartPidSum", REG_HOLDING, 75, 40076, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External additional heater start (PID sum)"},
{"setHeatpumpCondenserPumpLowestAllowedSpeed", REG_HOLDING, 76, 40077, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Condenser pump lowest allowed speed (%)"},
{"setHeatpumpBrinePumpLowestAllowedSpeed", REG_HOLDING, 77, 40078, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine pump lowest allowed speed (%)"},
{"setHeatpumpExternalAdditionalHeaterStopPidSum", REG_HOLDING, 78, 40079, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External additional heater stop (PID sum)"},
{"setHeatpumpCondenserPumpHighestAllowedSpeed", REG_HOLDING, 79, 40080, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Condenser pump highest allowed speed (%)"},
{"setHeatpumpBrinePumpHighestAllowedSpeed", REG_HOLDING, 80, 40081, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine pump highest allowed speed (%)"},
{"setHeatpumpCondenserPumpStandbySpeed", REG_HOLDING, 81, 40082, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Condenser pump standby speed (%)"},
{"setHeatpumpBrinePumpStandbySpeed", REG_HOLDING, 82, 40083, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Brine pump standby speed (%)"},
{"setHeatpumpMinAllowedGearPool", REG_HOLDING, 85, 40086, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Minimum allowed gear in pool *3"},
{"setHeatpumpMaxAllowedGearPool", REG_HOLDING, 86, 40087, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Maximum allowed gear in pool *3"},
{"setHeatpumpMinAllowedGearCooling", REG_HOLDING, 87, 40088, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Minimum allowed gear in cooling *3"},
{"setHeatpumpMaxAllowedGearCooling", REG_HOLDING, 88, 40089, 1, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "Maximum allowed gear in cooling *3"},
{"setCoolingStartTemp", REG_HOLDING, 105, 40106, 100, MODEL_MEGA | MODEL_INVERTER, "Cooling", "CoolingTank", "Start temp for cooling (EM)"},
{"setCoolingStopTemp", REG_HOLDING, 106, 40107, 100, MODEL_MEGA | MODEL_INVERTER, "Cooling", "CoolingTank", "Stop temp for cooling (EM)"},
{"setHeatingMixValve1MinLimitationSetPointCurve", REG_HOLDING, 107, 40108, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Min limitation Set point curve radiator Mix valve 1"},
{"setHeatingMixValve1MaxLimitationSetPointCurve", REG_HOLDING, 108, 40109, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Max limitation Set point curve radiator Mix valve 1"},
{"setHeatingMixValve1HeatCurveYCoordinate1", REG_HOLDING, 109, 40110, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Set point curve, Y-coordinate 1 Mix valve 1 (highest outdoor temperature)"},
{"setHeatingMixValve1HeatCurveYCoordinate2", REG_HOLDING, 110, 40111, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Set point curve, Y-coordinate 2 Mix valve 1"},
{"setHeatingMixValve1HeatCurveYCoordinate3", REG_HOLDING, 111, 40112, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Set point curve, Y-coordinate 3 Mix valve 1"},
{"setHeatingMixValve1HeatCurveYCoordinate4", REG_HOLDING, 112, 40113, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Set point curve, Y-coordinate 4 Mix valve 1"},
{"setHeatingMixValve1HeatCurveYCoordinate5", REG_HOLDING, 113, 40114, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Set point curve, Y-coordinate 5 Mix valve 1"},
{"setHeatingMixValve1HeatCurveYCoordinate6", REG_HOLDING, 114, 40115, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Set point curve, Y-coordinate 6 Mix valve 1"},
{"setHeatingMixValve1HeatCurveYCoordinate7", REG_HOLDING, 115, 40116, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Set point curve, Y-coordinate 7 Mix valve 1 (lowest outdoor temperature)"},
{"setHeatingFixedSystemSupplySetPoint", REG_HOLDING, 116, 40117, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "Unit", "Fixed system supply set point, requires defacto address 42 to be enabled"},
{"setHeatingMixValve2MinLimitationSetPointCurve", REG_HOLDING, 199, 40200, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Min limitation Set point curve radiator Mix valve 2"},
{"setHeatingMixValve2MaxLimitationSetPointCurve", REG_HOLDING, 200, 40201, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Max limitation Set point curve radiator Mix valve 2"},
{"setHeatingMixValve2HeatCurveYCoordinate1", REG_HOLDING, 201, 40202, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Set point curve, Y-coordinate 1 Mix valve 2 (highest outdoor temperature)"},
{"setHeatingMixValve2HeatCurveYCoordinate2", REG_HOLDING, 202, 40203, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Set point curve, Y-coordinate 2 Mix valve 2"},
{"setHeatingMixValve2HeatCurveYCoordinate3", REG_HOLDING, 203, 40204, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Set point curve, Y-coordinate 3 Mix valve 2"},
{"setHeatingMixValve2HeatCurveYCoordinate4", REG_HOLDING, 204, 40205, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Set point curve, Y-coordinate 4 Mix valve 2"},
{"setHeatingMixValve2HeatCurveYCoordinate5", REG_HOLDING, 205, 40206, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Set point curve, Y-coordinate 5 Mix valve 2"},
{"setHeatingMixValve2HeatCurveYCoordinate6", REG_HOLDING, 206, 40207, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Set point curve, Y-coordinate 6 Mix valve 2"},
{"setHeatingMixValve2HeatCurveYCoordinate7", REG_HOLDING, 207, 40208, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve2", "Set point curve, Y-coordinate 7 Mix valve 2 (lowest outdoor temperature)"},
{"setHeatingMixValve3MinLimitationSetPointCurve", REG_HOLDING, 208, 40209, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Min limitation Set point curve radiator Mix valve 3"},
{"setHeatingMixValve3MaxLimitationSetPointCurve", REG_HOLDING, 209, 40210, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Max limitation Set point curve radiator Mix valve 3"},
{"setHeatingMixValve3HeatCurveYCoordinate1", REG_HOLDING, 210, 40211, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Set point curve, Y-coordinate 1 Mix valve 3 (highest outdoor temperature)"},
{"setHeatingMixValve3HeatCurveYCoordinate2", REG_HOLDING, 211, 40212, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Set point curve, Y-coordinate 2 Mix valve 3"},
{"setHeatingMixValve3HeatCurveYCoordinate3", REG_HOLDING, 212, 40213, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Set point curve, Y-coordinate 3 Mix valve 3"},
{"setHeatingMixValve3HeatCurveYCoordinate4", REG_HOLDING, 213, 40214, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Set point curve, Y-coordinate 4 Mix valve 3"},
{"setHeatingMixValve3HeatCurveYCoordinate5", REG_HOLDING, 214, 40215, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Set point curve, Y-coordinate 5 Mix valve 3"},
{"setHeatingMixValve3HeatCurveYCoordinate6", REG_HOLDING, 215, 40216, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Set point curve, Y-coordinate 6 Mix valve 3"},
{"setHeatingMixValve3HeatCurveYCoordinate7", REG_HOLDING, 216, 40217, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve3", "Set point curve, Y-coordinate 7 Mix valve 3 (lowest outdoor temperature)"},
{"setHeatingMixValve4MinLimitationSetPointCurve", REG_HOLDING, 239, 40240, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Min limitation Set point curve radiator Mix valve 4"},
{"setHeatingMixValve4MaxLimitationSetPointCurve", REG_HOLDING, 240, 40241, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Max limitation Set point curve radiator Mix valve 4"},
{"setHeatingMixValve4HeatCurveYCoordinate1", REG_HOLDING, 241, 40242, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Set point curve, Y-coordinate 1 Mix valve 4 (highest outdoor temperature)"},
{"setHeatingMixValve4HeatCurveYCoordinate2", REG_HOLDING, 242, 40243, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Set point curve, Y-coordinate 2 Mix valve 4"},
{"setHeatingMixValve4HeatCurveYCoordinate3", REG_HOLDING, 243, 40244, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Set point curve, Y-coordinate 3 Mix valve 4"},
{"setHeatingMixValve4HeatCurveYCoordinate4", REG_HOLDING, 244, 40245, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Set point curve, Y-coordinate 4 Mix valve 4"},
{"setHeatingMixValve4HeatCurveYCoordinate5", REG_HOLDING, 245, 40246, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Set point curve, Y-coordinate 5 Mix valve 4"},
{"setHeatingMixValve4HeatCurveYCoordinate6", REG_HOLDING, 246, 40247, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Set point curve, Y-coordinate 6 Mix valve 4"},
{"setHeatingMixValve4HeatCurveYCoordinate7", REG_HOLDING, 247, 40248, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve4", "Set point curve, Y-coordinate 7 Mix valve 4 (lowest outdoor temperature)"},
{"setHeatingMixValve5MinLimitationSetPointCurve", REG_HOLDING, 248, 40249, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Min limitation Set point curve radiator Mix valve 5"},
{"setHeatingMixValve5MaxLimitationSetPointCurve", REG_HOLDING, 249, 40250, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Max limitation Set point curve radiator Mix valve 5"},
{"setHeatingMixValve5HeatCurveYCoordinate1", REG_HOLDING, 250, 40251, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Set point curve, Y-coordinate 1 Mix valve 5 (highest outdoor temperature)"},
{"setHeatingMixValve5HeatCurveYCoordinate2", REG_HOLDING, 251, 40252, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Set point curve, Y-coordinate 2 Mix valve 5"},
{"setHeatingMixValve5HeatCurveYCoordinate3", REG_HOLDING, 252, 40253, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Set point curve, Y-coordinate 3 Mix valve 5"},
{"setHeatingMixValve5HeatCurveYCoordinate4", REG_HOLDING, 253, 40254, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Set point curve, Y-coordinate 4 Mix valve 5"},
{"setHeatingMixValve5HeatCurveYCoordinate5", REG_HOLDING, 254, 40255, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Set point curve, Y-coordinate 5 Mix valve 5"},
{"setHeatingMixValve5HeatCurveYCoordinate6", REG_HOLDING, 255, 40256, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Set point curve, Y-coordinate 6 Mix valve 5"},
{"setHeatingMixValve5HeatCurveYCoordinate7", REG_HOLDING, 256, 40257, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve5", "Set point curve, Y-coordinate 7 Mix valve 5 (lowest outdoor temperature)"},
{"setPoolReturnTempFromPoolToHeatExchanger", REG_HOLDING, 299, 40300, 10, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Set point return temp from pool to heat exchanger (EM)"},
{"setPoolHysteresis", REG_HOLDING, 300, 40301, 10, MODEL_MEGA | MODEL_INVERTER, "Pool", "Unit", "Set point pool hysteresis (EM)"},
{"setHeatingMixValve1SupplyLineTempPassiveCooling", REG_HOLDING, 302, 40303, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Set point for supply line temp passive cooling with mixing valve 1"},
{"setHeatingMinOutdoorTempCoolingPermitted", REG_HOLDING, 303, 40304, 100, MODEL_MEGA | MODEL_INVERTER, "Heating", "MixValve1", "Set point minimum outdoor temp when cooling is permitted"},
{"setHeatpumpExternalHeaterOutdoorTempLimit", REG_HOLDING, 304, 40305, 100, MODEL_MEGA | MODEL_INVERTER, "Heatpump", "Unit", "External heater outdoor temp limit"},
{"setHeatingMixValve2SelectedMode", REG_HOLDING, 305, 40306, 1, MODEL_MEGA, "Heating", "MixValve2", "Selected mode for mixing valve 2, 0:Heat, 1:Cool, 2:Auto (EM3 only)"},
{"setHeatingMixValve2DesiredCoolingTempSetPoint", REG_HOLDING, 306, 40307, 100, MODEL_MEGA, "Heating", "MixValve2", "Desired cooling temperature setpoint mixing valve 2 (EM3 only)"},
{"setHeatingMixValve2SeasonalCoolingTemp", REG_HOLDING, 307, 40308, 100, MODEL_MEGA, "Heating", "MixValve2", "Seasonal cooling temperature (outdoor temp.), mixing valve 2 (EM3 only)"},
{"setHeatingMixValve2SeasonalHeatingTemp", REG_HOLDING, 308, 40309, 100, MODEL_MEGA, "Heating", "MixValve2", "Seasonal heating temperature (outdoor temp.), mixing valve 2 (EM3 only)"},
{"setHeatingMixValve3SelectedMode", REG_HOLDING, 309, 40310, 1, MODEL_MEGA, "Heating", "MixValve3", "Selected mode for mixing valve 3, 0:Heat, 1:Cool, 2:Auto (EM3 only)"},
{"setHeatingMixValve3DesiredCoolingTempSetPoint", REG_HOLDING, 310, 40311, 100, MODEL_MEGA, "Heating", "MixValve3", "Desired cooling temperature setpoint mixing valve 3 (EM3 only)"},
{"setHeatingMixValve3SeasonalCoolingTemp", REG_HOLDING, 311, 40312, 100, MODEL_MEGA, "Heating", "MixValve3", "Seasonal cooling temperature (outdoor temp.), mixing valve 3 (EM3 only)"},
{"setHeatingMixValve3SeasonalHeatingTemp", REG_HOLDING, 312, 40313, 100, MODEL_MEGA, "Heating", "MixValve3", "Seasonal heating temperature (outdoor temp.), mixing valve 3 (EM3 only)"},
{"setHeatingMixValve4SelectedMode", REG_HOLDING, 313, 40314, 1, MODEL_MEGA, "Heating", "MixValve4", "Selected mode for mixing valve 4, 0:Heat, 1:Cool, 2:Auto (EM3 only)"},
{"setHeatingMixValve4DesiredCoolingTempSetPoint", REG_HOLDING, 314, 40315, 100, MODEL_MEGA, "Heating", "MixValve4", "Desired cooling temperature setpoint mixing valve 4 (EM3 only)"},
{"setHeatingMixValve4SeasonalCoolingTemp", REG_HOLDING, 315, 40316, 100, MODEL_MEGA, "Heating", "MixValve4", "Seasonal cooling temperature (outdoor temp.), mixing valve 4 (EM3 only)"},
{"setHeatingMixValve4SeasonalHeatingTemp", REG_HOLDING, 316, 40317, 100, MODEL_MEGA, "Heating", "MixValve4", "Seasonal heating temperature (outdoor temp.), mixing valve 4 (EM3 only)"},
{"setHeatingMixValve5SelectedMode", REG_HOLDING, 317, 40318, 1, MODEL_MEGA, "Heating", "MixValve5", "Selected mode for mixing valve 5, 0:Heat, 1:Cool, 2:Auto (EM3 only)"},
{"setHeatingMixValve5DesiredCoolingTempSetPoint", REG_HOLDING, 318, 40319, 100, MODEL_MEGA, "Heating", "MixValve5", "Desired cooling temperature setpoint mixing valve 5 (EM3 only)"},
{"setHeatingMixValve5SeasonalCoolingTemp", REG_HOLDING, 319, 40320, 100, MODEL_MEGA, "Heating", "MixValve5", "Seasonal cooling temperature (outdoor temp.), mixing valve 5 (EM3 only)"},
{"setHeatingMixValve5SeasonalHeatingTemp", REG_HOLDING, 320, 40321, 100, MODEL_MEGA, "Heating", "MixValve5", "Seasonal heating temperature (outdoor temp.), mixing valve 5 (EM3 only)"},

